// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Enrich telemetry attributes with compliance control data
	// (POST /v1/enrich)
	PostV1Enrich(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostV1Enrich operation middleware
func (siw *ServerInterfaceWrapper) PostV1Enrich(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostV1Enrich(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/v1/enrich", wrapper.PostV1Enrich)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RYb2/bvhH+KgduwDZAdpxm/+B3+bktGmBtvCTbmyYvaOpss6FIlTw59Yp89+Eoyvpj",
	"OWnR7Z0t8sjn7p67e6TvQrmidBYtBTH/LoLaYiHjz4UrSqOlVcj/ZJ5r0s5Ks/SuRE8ag5ivpQmYiRyD",
	"8rrkdTHvGEKOJLUJsPaugOvF7Xu4RVV5TXtYOEveGVh6t9YGpyITZedkBhY38M/fe1yLufjdWQv2LCE9",
	"a29LJ4rnTKD1Wm0LtHRLkqp4Xh9k/RzcGmiLoFrIrSmU3ikMYQ6hUvwjg8oWsiwxz6CUnrQ0GTgPlX20",
	"7smyC2irQsw/i2QhMtGYsH+1TXwYLUQmwqOOqw+ZwG+yKA2Kecea9mV8QF7bDXu29rLAJ+cfw48H5n1r",
	"85wJr8Pjj9ve8O5nNsOvlfaYs3dNanpwRqL+kAnSFF3qsOnglVt9QUWM6TiJxwlriJMuB23XzheSl2Ht",
	"fDeHMgQMgYEcsUqWpdFKrrTRtD++5Z3dae8smwaIh1rCbxTgaYsegbY6HADEozA63mTus1h6l1cqnpYx",
	"yTact4dMaMIiAjjKaHogvZd7/q8kSeM2V/kxun9Z/bVC0Dla0muNPjrOBA7D6KRT2IdDjrpIxfXt8nby",
	"2xjFlCTcOD8SnUVaiafKQps90FbSOIIVGmc3Acj17r2M1G7Kf+x+/Wuer1DbTaJALLuBz/+8nMz+Np2d",
	"j13tscBcR0697d4/hNNZbFqIR+WKAm2OOXSOgUCeo7ZPgFv+9JDdYOF2CN45giqgB1mHSdocNO9pGlKJ",
	"Hq4uP0LpjFY1+wZeDGpVcwhaTnXS+/BiIb7vNZqTHf5Argg1XRzBdurzqArXLxx+g5vKSEo00zavAvk9",
	"BJI2lz4PKcG4k6aShPmg+Pvl+Onq9m7y99ls8pcLrsfrxeTNz1Vjx6OXA9Fz/UDTNPqYIK3PQw/6kC8X",
	"E+bmYvHX6fnPYB3kvdeZe168nPebNB5OO6rDY6fDvphngzsc6eV8B8Q1PsgpHfP4pGkL1tlJP5lpoi68",
	"Jq3i9PygN1uRiY+Y66oQmfiHexKZuGpxSNOfp8ng5UKpsY4F591hrt3g1woDjZE2LkAp98bJmpOEXLbM",
	"XUnk9aqirro4ilWs6P1rk3lZ7xqCT8avoQ+lswFPpBepJ4QKJJlLkqCtMlXOjG1aLCsabTch65A6GxJj",
	"2qV1rTNbOdkRd4OJfHqEdgZjO73aYXU8WXQ+0vNPtfhfaMGjgrMj4vrdrvvvZIPqt51hU+iouFRhNcWf",
	"mRZDFd0N+49pvhG9d1gaZZj3zkcKD67OR6j24e5uyc2c1Xfc0WHJn2ezTNRVLOZCW7p405attoQb9Hxh",
	"gSHIzcjhEQk0y69VfLq+2T7m2vJQlCcKBnfc7BUCi63Y6+tSBLQbbbGmz6g0BXLOhBNt4F20/iSLESf5",
	"aaM6epfVYqxEzyHEPG5IQyYKFQ/IPVLVTJZNiXX00fJyTBXVl9xUBn9OlCZwvjJ4NLRbMH2JlqPdT7gG",
	"J1yDr6bwKFoDtMc55RN4ZB07cgkKLXlp9H8wH+2EAf0OfQqzd5z6kLyckJt0TZoOeW+bptltlVEr9dtl",
	"iGFLh8kwYXICb18b9xSmcMfSkQFohTWQADLAveVIy4q2zmuSpHcIwVWepVn/pajxIgO0cmU4Hdcl2rvD",
	"lFLOGFTkfE1aR1v0cG/DPrACAXJpeh1I11ILd9GDOMEboTaMYnqVyuDe+lbitaPkEBNlZAh6rVU8O0zv",
	"maTd90gZAtymSFwur0QmduhDncTZ9Hw6Y9K6Eq0stZiLi+lsehFfv2kbS+xsd35Wu1IX3NhA52FSUgBO",
	"OnG1PeJ+bKIH+CNON9MsZpLg6m3WhMfKArN6kly9/RO7x45T5W2A9mtKJ0ITjybWRufwlQxcLBa4+3ne",
	"n7tCasvtRqvpvY20QJuXTrMWC3FjfAkhBysEJY3BHFZ7kHaQ70WT7z8EUFUg7l31Fw/n66BzX4pJiDN3",
	"6QL9+7yWE0lTYqDfXL5vJjrLmnais+HZl1C/P9VT5rUZdKy0nvsVT77C+KBWMjGdb2az/wuAJJYigsG3",
	"iHq0rytj9qkoemkT0WItK0P/O2RxyI6AqSx+K1ExcTDtyUSoikJGVVR7NE7dWK+DEuVWxW2Cr3r+bwAA",
	"AP//8T6iih8UAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
