// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"
	"time"
)

// Defines values for ComplianceRiskLevel.
const (
	Critical      ComplianceRiskLevel = "Critical"
	High          ComplianceRiskLevel = "High"
	Informational ComplianceRiskLevel = "Informational"
	Low           ComplianceRiskLevel = "Low"
	Medium        ComplianceRiskLevel = "Medium"
)

// Defines values for EvidencePolicyEvaluationStatus.
const (
	Failed        EvidencePolicyEvaluationStatus = "Failed"
	NeedsReview   EvidencePolicyEvaluationStatus = "Needs Review"
	NotApplicable EvidencePolicyEvaluationStatus = "Not Applicable"
	NotRun        EvidencePolicyEvaluationStatus = "Not Run"
	Passed        EvidencePolicyEvaluationStatus = "Passed"
	Unknown       EvidencePolicyEvaluationStatus = "Unknown"
)

// Defines values for StatusId.
const (
	N0  StatusId = 0
	N1  StatusId = 1
	N2  StatusId = 2
	N3  StatusId = 3
	N99 StatusId = 99
)

// Defines values for StatusTitle.
const (
	COMPLIANT     StatusTitle = "COMPLIANT"
	EXEMPT        StatusTitle = "EXEMPT"
	NONCOMPLIANT  StatusTitle = "NON_COMPLIANT"
	NOTAPPLICABLE StatusTitle = "NOT_APPLICABLE"
	UNKNOWN       StatusTitle = "UNKNOWN"
)

// Compliance Compliance details from OCSF Security Control Profile.
type Compliance struct {
	// Control Security control information for compliance assessment
	Control ComplianceControl `json:"control"`

	// Frameworks Compliance framework and requirement information
	Frameworks ComplianceFrameworks `json:"frameworks"`

	// Risk Compliance risk assessment information
	Risk *ComplianceRisk `json:"risk,omitempty"`

	// Status Compliance Result
	Status Status `json:"status"`
}

// ComplianceControl Security control information for compliance assessment
type ComplianceControl struct {
	// Applicability Environments or contexts where this control applies
	Applicability *[]string `json:"applicability,omitempty"`

	// CatalogId Unique identifier for the security control catalog or framework
	CatalogId string `json:"catalogId"`

	// Category Category or family that the security control belongs to
	Category string `json:"category"`

	// Id Unique identifier for the security control being assessed
	Id string `json:"id"`

	// RemediationDescription Description of the recommended remediation strategy for this control
	RemediationDescription *string `json:"remediationDescription,omitempty"`
}

// ComplianceFrameworks Compliance framework and requirement information
type ComplianceFrameworks struct {
	// Frameworks Regulatory or industry standards being evaluated for compliance
	Frameworks []string `json:"frameworks"`

	// Requirements Compliance requirement identifiers from the frameworks being evaluated
	Requirements []string `json:"requirements"`
}

// ComplianceRisk Compliance risk assessment information
type ComplianceRisk struct {
	// Level Risk level associated with non-compliance
	Level *ComplianceRiskLevel `json:"level,omitempty"`
}

// ComplianceRiskLevel Risk level associated with non-compliance
type ComplianceRiskLevel string

// EnrichmentRequest defines model for EnrichmentRequest.
type EnrichmentRequest struct {
	// Evidence Complete evidence log from policy engines and compliance assessment tools
	Evidence Evidence `json:"evidence"`
}

// EnrichmentResponse Enriched compliance finding with risk attributes and threat mappings.
type EnrichmentResponse struct {
	// Compliance Compliance details from OCSF Security Control Profile.
	Compliance Compliance `json:"compliance"`
}

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Evidence Complete evidence log from policy engines and compliance assessment tools
type Evidence struct {
	// PolicyEngineName Name of the policy engine that performed the evaluation or enforcement action
	PolicyEngineName string `json:"policyEngineName"`

	// PolicyEvaluationStatus Result of the policy evaluation
	PolicyEvaluationStatus EvidencePolicyEvaluationStatus `json:"policyEvaluationStatus"`

	// PolicyRuleId Unique identifier for the policy rule being evaluated or enforced
	PolicyRuleId string `json:"policyRuleId"`

	// RawData Raw JSON output from the policy engine
	RawData json.RawMessage `json:"rawData,omitempty"`

	// Timestamp The time when the raw evidence was generated
	Timestamp time.Time `json:"timestamp"`
}

// EvidencePolicyEvaluationStatus Result of the policy evaluation
type EvidencePolicyEvaluationStatus string

// Status Compliance Result
type Status struct {
	// Id Compliance status ID (0=COMPLIANT, 1=NON_COMPLIANT, 2=EXEMPT, 3=NOT_APPLICABLE, 99=UNKNOWN).
	Id *StatusId `json:"id,omitempty"`

	// Title Compliance status.
	Title StatusTitle `json:"title"`
}

// StatusId Compliance status ID (0=COMPLIANT, 1=NON_COMPLIANT, 2=EXEMPT, 3=NOT_APPLICABLE, 99=UNKNOWN).
type StatusId int

// StatusTitle Compliance status.
type StatusTitle string

// PostV1EnrichJSONRequestBody defines body for PostV1Enrich for application/json ContentType.
type PostV1EnrichJSONRequestBody = EnrichmentRequest
